---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  labels:
    app: CMS
    author: intelliqit
spec:
  containers:
    - name: ghost
      image: ghost
      ports:
        - containerPort: 2368
          hostPort: 9090
      env:
        - name: NODE_ENV
          value: development
...

