---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgres-rs
  namespace: test-ns
  labels:
    type: db
    author: intelliqit
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: postgres-pod
      labels:
        type: db
    spec:
      containers:
        - name: mypostgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: intelliqit
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_DB
              value: mydb
...

