---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: db
spec:
  containers:
    - name: mydb
      image: mysql
      volumeMounts:
       - name: mysql-volume
         mountPath: /var/lib/mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: intelliqit
  volumes:
   -  name: mysql-volume
      persistentVolumeClaim:
        claimName: mysql-pvc
...
